name: census-analysis
channels:
    - conda-forge
dependencies:
  - python=3.9.7
  - pandas
  - jupyterlab
  - ipywidgets
  - nodejs
  - pip
  - openpyxl
  - h5py
  - PyTables
  - voila
  - pip:
    - CensusData==1.15
    - data_cache==0.1.6